### ISSUE TITLE
Unable to integrate with Slack

### ISSUE THREAD

**Issue by dwesty** [Upward-Spiral-Science/uhhh#4]
I think it has something to do with who owns this org. I see quite a few options available, and since I'm the owner of the private org Proscia, all those repos show up too. That leads me to believe we need @jovo and @gkiar need to authorize this.

![image](https://cloud.githubusercontent.com/assets/6182431/13205672/602f0978-d8bb-11e5-90c2-df80f44ca35e.png)

Our intended integration is for all gh activity (commits, issues) on all branches of "uhhh" to post to "#uhhh" channel in Slack

**Comment by gkiar** [comment]
Looks like you fixed?

## 

Greg Kiar gkiar07@gmail.com

**Comment by jovo** [comment]
i didn't do anything :)
but if you guys swing by tues before class, we/@gkiar can help?

On Mon, Feb 22, 2016 at 8:32 AM, Greg Kiar notifications@github.com wrote:

> Looks like you fixed?
> 
> ## 
> 
> Greg Kiar gkiar07@gmail.com
> 
> On Sun, Feb 21, 2016 at 4:54 PM, David West notifications@github.com
> wrote:
> 
> > Assigned #4 https://github.com/Upward-Spiral-Science/uhhh/issues/4 to
> > @gkiar https://github.com/gkiar.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/Upward-Spiral-Science/uhhh/issues/4#event-558682511
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Upward-Spiral-Science/uhhh/issues/4#issuecomment-187174526
> .

## 

the glass is all full:  half water, half air.
neurodata.io
